### ISSUE TITLE
getMedianAndStandardDeviation

### ISSUE THREAD

**Issue by ksiminski** [vnuczek/neuro-fuzzy-library#7]
Coś jest nie tak z tą metodą:
https://github.com/vnuczek/neuro-fuzzy-library/blob/99ccd86e1acbc17f748e2436f3debf2302089611/source/auxiliary/utility-math.h#L195
W nazwie ma …Median…, ale wyznacza średnią. No i teraz jest pytanie:
¿Czy ta metoda ma po prostu błędną nazwę i powinna się nazywać …Mean…? 
albo
¿Czy nazwa jest dobra, ale metoda nie liczy mediany, ale średnią?

**Comment by ksiminski** [comment]
Thank you for the fix! However, I have two remarks:

1. In the previous implementation, the name of the function was incorrect but the implementation was faultless. Please restore the previous body of the function __but__ rename it MeanAndStandardDeviation. A method for the mean and stdDev is a very useful one. So let's have it in the repo with the correct name.
2. The MedianAndStandardDeviation method is a very nice one. I have a tiny remark. You do not need to implement the quickselect algorithm. It is implemented in an effective way as std::nth_element in the standard library. My hint is just to use it.

**Comment by vnuczek** [comment]
Implemented comments

**Comment by ksiminski** [comment]
Well done! Thank you, Konrad! I have no more remarks. The only thing to do is to close the issue :-)
